### ISSUE TITLE
error when running a tutorial

### ISSUE THREAD

**Issue by otuz1** [rstudio/learnr#169]
I am new to R. I am trying to follow a tutorial for R.

After I load the learnr package with library(learnr), I try to run a tutorial with learnr::run_tutorial("hello", package="learnr"), I get the following error in my console:

```
Loading required package: shiny

Listening on http://127.0.0.1:5950
Warning: Error in value[[3L]]: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'font-awesome-4.5.0'; `directoryPath` = ''
  [No stack trace available]
```

At the same time a page is opened on http://127.0.0.1:5950/ displaying the following error:

> ERROR: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'font-awesome-4.5.0'; `directoryPath` = ''

How can I fix this?

**Comment by jjallaire** [comment]
@rich-iannone It's possible that our update of font-awesome might have caused a problem here (although as far as I know re-knitting should always fix these types of errors). Could you try creating a tutorial with the older version of R Markdown that uses older Font Awesome then upgrading and see what happens?

@jcheng5 As far as I know re-knitting should fix this but @profandyfield reports that it didn't in his case.

**Comment by profandyfield** [comment]
I've just tried re-rendering a tutorial using rmarkdown version 1.9 and it renders fine - error is gone. Tried rendering the same tutorial under rmarkdown 1.10 and the error is back.

**Comment by jjallaire** [comment]
@rich-iannone we should be able to repro this then. @profandyfield Can you provide a minimal version of the tutorial that repros the problem?

**Comment by profandyfield** [comment]
Ok, so while trying to create a stripped down version of one of the tutorials I discovered that if I re-render (rmarkdown 1.10) the tutorial without editing (which is what I had been doing because I don't need to edit them) then I get the error. If I edit (for example delete a character then type it again so that the .Rmd has to save before rendering) the error goes away and it renders. I tried on a different tutorial within the same package and exactly the same. 

Are there any plans to stop the need to re-render (or indeed edit and re-render) every time R updates. I had a similar issue last time R updated - I had to manually re-render the 16 tutorials in my package so that they'd work for anyone using the most recent R. I mean, that's fine, but there are more productive ways to spend half and hour. Failing that, is there a way to batch render tutorials that are hosted within a package? (a sort of 'render all' command)?
thanks for your help BTW - really appreciate it.

**Comment by jjallaire** [comment]
Ah, that makes perfect sense! (as we only re-render when the Rmd changes). Removing the .html file will also work.

What we really need to do is save the versions of all packages that we draw dependencies from and then automatically re-render when any of those versions changes.

**Comment by kevinushey** [comment]
FWIW I bumped into this when trying to re-render the sandbox tutorial `.Rmd` we have in the package for some local testing; deleting the old `.html` file within resolved the issue but that's not a particularly obvious solution.

**Comment by otuzla** [comment]
@profandyfield 

> I have the same issue with my adventr package of tutorials

I have read your book _An adventure in statistics_ . The reason I stumbled on this issue is because I am trying to start the adventr tutorials.

What do I need to right now to succesfully run the tutorials?

**Comment by profandyfield** [comment]
great - thanks for letting me know it now works! Hope you find the tutorials useful.

andy

**Comment by RodrigoDalBen** [comment]
Hello all, 
I had the same problem, so I re-installed "adventr". However, I encountered another problem when trying to run tutorial 11: 

> library(adventr)
> learnr::run_tutorial("adventr_11", package = "adventr")
Error: lexical error: invalid char in json text.
                                       <<<<<<< HEAD {"type":"list","at
                     (right here) ------^

Tutorials 1, 2, 3 works fine, but from 04 on the same error occur. How can I fix this?

**Comment by profandyfield** [comment]
I don't think this is a learnr issue, so I've reposted [here](https://github.com/profandyfield/adventr/issues/4)

**Comment by lbcollins** [comment]
@jjallaire  Do you plan to commit re-rendered html using rmarkdown 1.10? I gather from the discussion above that this may solve the problem when running `learnr::run_tutorial("hello", package="learnr")`. Thanks.

**Comment by jjallaire** [comment]
@schloerke Could you do this?

**Comment by schloerke** [comment]
@jjallaire Sure.  I'll re-run the learnr tutorials and add a note in the news for others to do the same.

**Comment by schloerke** [comment]
I believe it involves more than just a re-render of the documents. As now users with rmarkdown v1.9 will have issues with pre-rendered rmarkdown v1.10 documents.  (Confirmed on my machine.) 

@jjallaire Is there any location in the shiny-prerendered output that contains the rmarkdown version, similar to how roxygen does with man files?  If not, we could also look into having the rmarkdown version put into a meta field in the `<head>` of the html.

**Comment by jjallaire** [comment]
@schloerke There isn't anywhere right, but there are lots of places where structured metadata is written so we should be able to accommodate that info. Here you can see we serialize the HTML dependencies for the document:

https://github.com/rstudio/learnr/blob/master/inst/tutorials/hello/hello.html#L68-L72

So there is a general mechanism for writing and reading JSON from within the HTML.

Incidentally, I think some of the problem with version instability is caused by the fact that when we save HTML dependencies we save the path to the dependency within the package (and that path in turn often includes a version number). I think to really root out all of these problems we need to be able to serialize dependencies in a way that's directory name independent.

**Comment by schloerke** [comment]
@jjallaire Have addressed the issue in https://github.com/rstudio/rmarkdown/pull/1420.

Talking with @jcheng5 , we think it would be a good idea to inspect the document and force a new render if the utilized packages within the file are different from what the user has installed as well.  Such as `myPkg v1` was used in example 1 in the prerendered document, but the user as `myPkg v2`.  I think it would be fair that the document should be rendered again.

Seem like a good check to add?

**Comment by jjallaire** [comment]
I agree about re-rendering when the utilized packages change.

**Comment by yihui** [comment]
The problem should be gone with `devtools::install_github('rstudio/rmarkdown')` (thanks @schloerke).

**Comment by schloerke** [comment]
`devtools::install_github("rstudio/learnr")` will also install the dev version of `rmarkdown`

**Comment by cadlam** [comment]
So I know this issue is closed, but I am having exactly the same problem as described by @otuz1 and @profandyfield when I try to load the "adventr" tutorials. I have the latest dev versions of rmarkdown and learnr. I'm really looking forward to the adventr tutorials and would appreciate a solution. Thanks!

**Comment by schloerke** [comment]
@cadlam Can you paste in your whole error message below? And also `devtools::session_info()`

**Comment by schloerke** [comment]
Locking issue.  Please open a new issue and reference this one in your description
